#!/bin/sh
#
# Runs during git flow release finish
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the release prefix)
# Return VERSION - When VERSION is returned empty gitflow will stop as
#                  the version is necessary
VERSION=$1
ORIGIN=$2
BRANCH=$3

# Implement your script here.

# Return the VERSION
echo ${VERSION}
exit 0
