#!/bin/sh
#
# Runs during git flow release start
#
# Positional arguments:
# $1    Version
#
# Return VERSION - When VERSION is returned empty, git-flow will stop as the
# version is necessary
#
VERSION=$1

# Implement your script here.

# Return the VERSION
echo ${VERSION}
exit 0
