#!/bin/sh
#
# Runs at the end of git flow release start
#
# Positional arguments:
# $1    The origin remote
# $2    The full branch name (including the release prefix)
# $3    The base from which this release is started
#
ORIGIN=$1
BRANCH=$2
BASE=$3

# Implement your script here.

exit 0
