#!/bin/sh
#
# Runs at the end of git flow release delete
#
# Positional arguments:
# $1    The origin remote
# $2    The full branch name (including the release prefix)
#
ORIGIN=$1
BRANCH=$2

# Implement your script here.

exit 0
