#!/bin/sh
#
# Runs before git flow release track
#
# Positional arguments:
# $1    The origin remote
# $2    The full branch name (including the release prefix)
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
ORIGIN=$1
BRANCH=$2

# Implement your script here.

# To terminate the git-flow action, return a non-zero exit code.
exit 0
