#!/bin/sh
#
# Runs before git flow hotfix delete
#
# Positional arguments:
# $1    The origin remote
# $2    The full branch name (including the hotfix prefix)
#
ORIGIN=$1
BRANCH=$2

# Implement your script here.

# To terminate the git-flow action, return a non-zero exit code.
exit 0
